kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/hugo
  settings:
    url: https://fr1nge.xyz
    validate: false
- name: greeting
  image: node
  commands:
  - pwd
  - ls
