pipeline:
  build:
    image: plugins/hugo
    validate: false
    url: https://fr1nge.xyz

  deploy:
    image: drillster/drone-rsync
    hosts: [ "192.168.1.5" ]
    port: 3471
    target: /volume/fr1nge.xyz
    source: public/*
    key:
      from_secret: rsync_key
    user: root
    secrets: [ rsync_key ]
